import { startLogin } from "@/const";
import { Button } from "@/components/ui/button";
import { ArrowLeft, ArrowRight, Check, CircleHelp, Eye, ShieldCheck } from "lucide-react";
import { Link } from "wouter";

const steps = [
  ["1", "Create your account", "Use secure sign-in to create a private workspace."],
  ["2", "Understand the boundaries", "Watchtower only uses sources you authorize and capabilities the source legitimately exposes."],
  ["3", "Choose connections", "Connect an officially supported account or use a clearly separated demonstration workspace."],
  ["4", "Review signals", "See sources, evidence classifications, risk contributions, and safe next actions in plain language."],
];

export default function Onboarding() {
  return <div className="min-h-screen bg-[#f8fafc] text-slate-950"><header className="container flex h-20 items-center justify-between"><Link href="/" className="flex items-center gap-3 font-semibold"><span className="grid h-9 w-9 place-items-center rounded-xl bg-slate-950 text-white"><Eye className="h-5 w-5" /></span>Watchtower</Link><Link href="/"><Button variant="ghost" className="rounded-xl text-slate-600"><ArrowLeft className="mr-2 h-4 w-4" /> Home</Button></Link></header><main className="container max-w-5xl py-10 sm:py-16"><div className="max-w-3xl"><div className="inline-flex items-center gap-2 rounded-full bg-cyan-50 px-3 py-1.5 text-xs font-semibold text-cyan-900"><ShieldCheck className="h-3.5 w-3.5" /> Honest from the first screen</div><h1 className="mt-6 text-4xl font-semibold tracking-[-0.04em] sm:text-5xl">A guided, consent-based start.</h1><p className="mt-5 text-lg leading-8 text-slate-600">Watchtower is designed to help you understand digital exposure without overstating what it knows. Before you connect a source, we explain its access, scope, and limits.</p></div><section className="mt-12 grid gap-4 md:grid-cols-2">{steps.map(([number, title, copy]) => <article key={number} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><span className="grid h-8 w-8 place-items-center rounded-full bg-slate-950 text-sm font-semibold text-white">{number}</span><h2 className="mt-5 text-lg font-semibold">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{copy}</p></article>)}</section><section className="mt-6 rounded-2xl border border-amber-200 bg-amber-50 p-6"><div className="flex gap-3"><CircleHelp className="mt-0.5 h-5 w-5 shrink-0 text-amber-900" /><div><h2 className="font-semibold text-amber-950">What Watchtower cannot claim</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-amber-950/80">Watchtower cannot identify a person who merely viewed your profile unless the platform explicitly provides that information. It cannot bypass platform security, access private account data without authorization, or turn an indicator into a verified fact.</p></div></div></section><div className="mt-10 flex flex-col gap-3 sm:flex-row"><Button onClick={() => startLogin()} size="lg" className="rounded-xl bg-slate-950 px-6 hover:bg-slate-800">Create a secure workspace <ArrowRight className="ml-2 h-4 w-4" /></Button><Link href="/app"><Button size="lg" variant="outline" className="w-full rounded-xl bg-white sm:w-auto"><Check className="mr-2 h-4 w-4" /> Explore the separated demo</Button></Link></div></main></div>;
}
